---
- name: Install Amazon PHP stack
  yum: name={{ item }} update_cache=yes state=latest
  with_items:
   - git
   - htop
   - dstat
   - mosh
   - tree
   - httpd24
   - php56
   - php56-common
   - php56-xml
   - php56-pdo
   - php56-opcache
   - php56-pecl-apcu
   - php56-mcrypt
   - php56-process
   - php56-soap
   - php56-cli
   - php56-mysqlnd
   - php56-gd
   - php56-gmp
   - php56-mbstring
   - php56-devel
   - php56-imap
   - php56-pecl-igbinary
   - php56-pecl-igbinary-devel
   - php56-pecl-memcache.x86_64
   - php56-pecl-redis.x86_64
   - php56-pecl-imagick.x86_64

- name: Install Docker
  yum: name={{ item }} update_cache=yes state=latest
  with_items:
   - docker

- name: Start and enable Docker
  service: name=docker state=started enabled=yes

- name: Start and enable Apache
  service: name=httpd state=started enabled=yes

- name: Copy index.php to /var/www/html
  copy: src=../files/index.php dest=/var/www/html/index.php owner=root group=root
