---
- name: Get uname -s
  command: uname -s
  register: uname_s
- debug: var=uname_s

- name: Get uname -m
  command: uname -m
  register: uname_m

- debug: var=uname_s

- name: Install docker compose
  command: >
    curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout}} > /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    creates=/usr/local/bin/docker-compose
