---
- name: Get Lightning Distro.
  get_url: url=https://ftp.drupal.org/files/projects/lightning-8.x-1.03-core.tar.gz dest=/var/www/

- name: Unarchive lightning-8.x-1.03-core.tar.gz
  unarchive: src=/var/www/lightning-8.x-1.03-core.tar.gz dest=/var/www/lightning
