---
- name: Get Lightning Distro.
  get_url: url=https://ftp.drupal.org/files/projects/lightning-8.x-1.03-core.tar.gz dest=/var/www/

- name: Create /var/www/lightning directory
  file: path=/var/www/lightning state=directory mode=0755 owner=root group=root

- name: Unarchive lightning-8.x-1.03-core.tar.gz
  unarchive: src=/var/www/lightning-8.x-1.03-core.tar.gz dest=/var/www/lightning

- name: Remove current /var/www/html
  file: path=/var/www/html state=absent

- name: Create Symlink to lightning build
  file: src=/var/www/lightning/lightning-8.x-1.03 dest=/var/www/html state=link owner=root group=root

- name: Create files folder
  file: path=/var/www/lightning/lightning-8.x-1.03/sites/default/files state=directory owner=apache group=apache recursive=yes
