---
- name: Get Yum Repo file
  get_url: url=http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

- name: Import Jenkins key
  command: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins
  yum: name={{ item }}  update_cache=yes state=latest
  with_items:
    - java-1.8.0-openjdk
    - jenkins

- name: Start and enable Jenkins
  service: name=jenkins state=started enabled=yes

- name: Setup Up testing directory
  file: path=/opt/site_tests state=directory mode=0744 owner=root group=root

- name: Copy in custom composer.json
  template: src=templates/composer.json.j2 dest=/opt/site_tests/composer.json

- name: Setup test structure
  command: /usr/local/bin/composer install
  args:
    chdir: /opt/site_tests

