---
- name: Setup Docker repo
  copy: src=./files/docker.repo dest=/etc/yum.repos.d/docker.repo mode=0644 owner=root group=root

- name: Install Redhat PHP stack
  yum: name={{ item }} update_cache=yes state=latest
  with_items:
   - git
   - dstat
   - tree
   - httpd
   - php
   - php-cli
   - php-gd
   - php-ldap
   - php-mysql
   - php-pdo
   - php-pear
   - php-pecl-memcache
   - php-process
   - php-xml

- name: Install Docker
  yum: name={{ item }} update_cache=yes state=latest
  with_items:
   - docker-engine

- name: Start and enable Docker
  service: name=docker state=started enabled=yes

- include: install-docker-compose.yml
